### ISSUE TITLE
move checklist editor deployment to Harlow

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#171]
This can wait for Post Production while we use the proxy configuration to enable access for HX to HL.

## Tasks for migration to HL:
- [x] wwwint in Harlow
  - [x] access to k8 in HL
  - [x] biovalidator
    - [x] configure gitlab environments
    - [x] traffic manager rules
  - [x] deploy schema store [MR](https://gitlab.ebi.ac.uk/wp/wp-traffic-manager/-/merge_requests/1535/)
    - [x] configure gitlab environments
    - [x] traffic manager rules
  - [x] deploy checklist editor
    - [x] configure gitlab environments
    - [x] traffic manager rules
- [x] wwwdev 
   - [x] deploy biovalidator to HX
   - [x] deploy biovalidator to HL
   - [x] deploy checklist editor to HX
   - [x] deploy checklist editor to HL
   - [x] deploy schema store to HX
   - [x] deploy schema store to HL , [MR](https://gitlab.ebi.ac.uk/wp/vtm-terraform-config/-/merge_requests/67/)
   - [x] traffic manager rule
   - [x] monitoring rule (to initiate fail over)
     - [x] monitors for failover. url: `/biosamples/schema-store/actuator/health`
     - [x] monitors for failover. url: `/biosamples/checklist-editor`
     - [x] monitors for failover. url: `/biosamples/biovalidator/` ([gitlab MR](https://gitlab.ebi.ac.uk/wp/vtm-terraform-config/-/merge_requests/62))
- [ ] prod 
   - [x] deploy biovalidator to HX
   - [x] deploy biovalidator to HL
   - [x] deploy checklist editor to HX
   - [x] deploy checklist editor to HL
   - [x] deploy schema store to HX
   - [x] deploy schema store to HL
   - [ ] once mongo access is granted, check connectivity between all components (can not be tested at this stage)
   - [x] traffic manager rule - checklist editor [MR ticket](https://embl.service-now.com/esc?id=ticket&is_new_order=true&table=sc_req_item&sys_id=5c3fcae583771610916fd5547daad34b)
   - [x] traffic manager rule - schema store [MR ticket](https://embl.service-now.com/esc?id=ticket&is_new_order=true&table=sc_req_item&sys_id=b57a31e583f31610916fd5547daad3be) 
   - [x] traffic manager rule - biovalidator [MR ticket](https://embl.service-now.com/esc?id=ticket&is_new_order=true&table=sc_req_item&sys_id=39aa292d83731610916fd5547daad30c)
   - [x] monitoring rule (to initiate fail over)
- [x] giltab k8s config variable for HL (it is a group variable in the FAIRification group)
- [x] mongo db access
    - [x] create mongodb secret for all environment
   - [x] mongo db access for Dev and Test
   - [x] prod mongodb access from both HX and HL : [RITM0023319](https://embl.service-now.com/esc?id=ticket&is_new_order=true&table=sc_req_item&sys_id=a43d828183231610916fd5547daad32a)
- [ ] verification
  - [ ] run sanity checklist scenario (perhaps using Isuru's postman collection)
  - [x] identifiers.org access from HL and HX prod (check if proxy required)
  - [x] verify connectivity to webin (check if proxy required)
  - [ ] Bring down prod and verify request are being served from failover for prod services
- [x] Rename any inconsistent names from Gitlab deployment and TM rules

## naming conventions:
- environments: [primary,fallback]_[int, dev, prod], e.g. _primary_dev_
- gitlab jobs: deploy_<env>_, e.g. _deploy_primary_dev_
- TM mapping: 
  - Add rules between biosamples block
  - Use similar environment conventions. biosamples-checklist-editor-int, biosamples-checklist-editor-primary-dev, biosamples-checklist-editor-fallback-dev (if new TM repository is grouped by environment, we can drop environment name from the name)

**Comment by Wkt8** [comment]
This needs to be done prior to production and will also fix #180

**Comment by snathanvj** [comment]
@theisuru I am working on moving biovalidator to HL and use HX as fallback. Let's discuss the details.

**Comment by snathanvj** [comment]
ISSUESS faced so far:

- [x] Ingress was failing - wp team resolved it : [INC0061572](https://embl.service-now.com/esc?id=ticket&table=incident&sys_id=969464c31b0792103182bb35464bcb7c)
- [x] wwwint rule mapping did not work for HL : [INC0061587](https://embl.service-now.com/esc?id=ticket&table=incident&sys_id=0ddca1df1bcbd2103182bb35464bcb09)
- [x] ingress misconfiguration issue for json-schema-store
- [x] Mongodb access from k8s cluster [RITM0023007](https://embl.service-now.com/esc?id=ticket&table=sc_req_item&sys_id=7ae2e5ec1b135a103182bb35464bcbbe)
- [x] Removed ingress for biovalidator as well as it is not required since @theisuru added baseUrl as container arg. [Biovalidator deployment code changes](https://github.com/elixir-europe/biovalidator/commit/fd76c5f0efec598cf2c4d36b67f1320ca4647ca9) , traffic manager update [MR](https://gitlab.ebi.ac.uk/wp/vtm-terraform-config/-/merge_requests/54/diffs)

**Comment by theisuru** [comment]
@snathanvj @amnonkhen @Jeena-Rajan  Please comment if you do not agree with this

All the services should run under `/biosamples`. 

For example `biovalidator` for `test` is served under  `https://wwwdev.ebi.ac.uk/biosamples/biovalidator`. This has been the case allways. 

Nothing is under `/ait`. If there was anything under `/ait`, this does not have to do anything with our current `biosamples` deployment.

**Comment by snathanvj** [comment]
Biovalidator was always under ait/biovalidator but someone changed wwwint and wwwdev. 

Earlier, we had two biovalidator deployment,
 One for internal use by biosamples , one for public use https://www.ebi.ac.uk/ait/biovalidator/

We have configured k8s based deployment only for external, left the VM based deployment untouched for biosamples use.

Though now we are replacing all the app context to be start with /biosamples/so_so , I have to keep ait/biovalidator for all environment(Note I haven't touched VM based deployment used by Biosamples) because it is being used by external parties. e.g., EGA

if you would like change the context path to biosamples/biovalidator please let me know , I will make the changes and redploy. Thanks.

**Comment by snathanvj** [comment]
Re-deploying wwwint and wwwdev to point to biosamples/biovalidator.

For production: Not deploying now, check if anybody using ait/biovalidator in monitor and then decide.

**Comment by snathanvj** [comment]
https://github.com/EBIBioSamples/json-schema-store/pull/65

PR for json-schema-store changes. All done.

Tested : 
- Some endpoints with bearer token using postman(fields and findByExample )
- Test environment deployed with fallback. Initially traffic was going to HL pod .Deleted deployment in primary(HL) and checked traffic was going to HX pod


https://github.com/elixir-europe/biovalidator/pull/82
 PR for biovalidator
- Test environment deployed with fallback. Initially traffic was going to HL pod .Deleted deployment in primary(HL) and checked traffic was going to HX pod

**Comment by snathanvj** [comment]
wwwint , wwwdev for both biovalidator and json-schema-store are done. wwwdev deployed with fallback.

**Comment by snathanvj** [comment]
**Resolved:** Ticket for kibana default index pattern does not work [INC0061788](https://embl.service-now.com/esc?id=ticket&is_new_order=true&table=incident&sys_id=fd9de545836fd210916fd5547daad3c6)

**Resolved:**  ticket for wwwint was pointing to HX instead of HL [INC0061696](https://embl.service-now.com/esc?id=ticket&table=incident&sys_id=5984916e1bdbd2503182bb35464bcbdf)

**Comment by snathanvj** [comment]
Deployed schema-store  production to HL and HX , waiting for [Network team to give mongodb access.](https://embl.service-now.com/esc?id=ticket&is_new_order=true&table=sc_req_item&sys_id=a43d828183231610916fd5547daad32a)

**Comment by amnonkhen** [comment]
@amnonkhen escalated [RITM0023319](https://wd103.myworkday.com/embl/d/task/25414$1.htmld) about HX/HL to mongo connectivity to Manuela Menchi on 14/2. 
Her update:

>  Let me take care of this. I have the DBA meeting in 6 minutes and Ill discuss this. I think I know what the issue may be: we have an SOP for this type of requests that is managed by the IT Support Desk. There must have been some misunderstanding and the ticket got stuck between IT Service Desk and DBAs. I'll unblock it. Apologies for this. and thank you for reaching out

**Comment by theisuru** [comment]
Now firewall rules are in place, we can continue with this. All services can be deployed and traffic manager rules can also be modified as biosamples at the moment uses internal urls of biovalidator and schema-store. 
Senthil and Isuru to discuss on Tuseday and complete.

**Comment by snathanvj** [comment]
Stopped https://www.ebi.ac.uk/ait/biovalidator/
Deployed https://www.ebi.ac.uk/biosamples/biovalidator/ to both primary and fallback prod.

Deployed schema-store to primary and fallback prod with dev mongo db ,prod mongodb was giving empty set.

@amnonkhen @theisuru **PROD schema-store deployment points to DEV MONGO DB**
http://hh-rke-wp-webadmin-69-worker-3.caas.ebi.ac.uk:31821/biosamples/schema-store/api/v2/mongoJsonSchemas?page=0&size=10&sort=id%2CASC
`{
    "_embedded": {
        "mongoJsonSchemas": []
    },
    "_links": {
        "self": {
            "href": "http://hh-rke-wp-webadmin-69-worker-3.caas.ebi.ac.uk:31821/biosamples/schema-store/api/v2/mongoJsonSchemas?page=0&size=10&sort=id,asc"
        },
        "profile": {
            "href": "http://hh-rke-wp-webadmin-69-worker-3.caas.ebi.ac.uk:31821/biosamples/schema-store/api/v2/profile/mongoJsonSchemas"
        },
        "search": {
            "href": "http://hh-rke-wp-webadmin-69-worker-3.caas.ebi.ac.uk:31821/biosamples/schema-store/api/v2/mongoJsonSchemas/search"
        }
    },
    "page": {
        "size": 10,
        "totalElements": 0,
        "totalPages": 0,
        "number": 0
    }`

@theisuru suspects it could be due to old format data but it was not failing still giving 200 http response.
