### ISSUE TITLE
additional checklist types in the editor

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#186]
- [ ] ENA Experiment (stakeholder: Peter)
- [ ] MorPhiC Experiment (stakeholder: Anu)
- [ ] Hierarchical checklists (stakeholder: EGA)

The first checklist is flat, so show me easy.
The other two have hierarchy. so the edit/create screen is more challenging.

Things to consider:
- Access control: editing/access by checklist type
- different json-schema format per checklist type
- how do we handle multi-tenancy? same db or different?
