### ISSUE TITLE
Convert ENA XML checklists into JSON Schema

### ISSUE THREAD

**Issue by theisuru** [ebi-ait/checklist#2]
ENA currently validates XML documents using checklists in XML format. 
Validation is to be migrated and delegated to BioSamples.

The current flow with affected areas to be decomissioned and new items to be implemented is shown in the following diagram (visible by viewing issue in github):
```mermaid
sequenceDiagram
    participant Client
    participant ENA
    participant BioSamples

    Client->>ENA: submit XML doc
    ENA->>ENA: fix document
    ENA->>ENA: convert to json in BioSamples format
    note over ENA: by submission team
    par existing flow: to be removed
       ENA->>BioSamples: send for accessioning
       ENA->>ENA: validate xml
       ENA->>ENA: build receipt
    end
    note over ENA: by FAIRification team
    par new flow: validation in BioSamples 
        ENA->>BioSamples: send for validation & accessioning
        BioSamples-->>ENA: validation results    
    end
    ENA->>ENA: build receipt
    ENA->>ENA: save in db
    ENA-->>Client: acknoledgement

```

Sub tasks:
- [ ] verify conversion of checklists to json schema format
  - see checklist-converter repo 
- [ ] retire existing ENA validation code
- [ ] change ENA code to read validation response from BioSamples
