### ISSUE TITLE
 Merge checklist-converter code with schema-store

### ISSUE THREAD

**Issue by amnonkhen** [ebi-ait/checklist#56]
- [x] upgrade to spring boot 3
- [x] merge xml 2 schema conversion (velocity template)
- [x] java upgrade
- [x] biovalidator version upgrade
- [ ] archive old repo and add a message to the top of readme
