### ISSUE TITLE
access control for checklist editor

### ISSUE THREAD

**Issue by Wkt8** [ebi-ait/checklist#92]
- authenticated access to ui using webin
  - [x] login screen
  - [x] read user identity from server
  - [x] read user roles from server
  - [x] pass token in requests to schema-store
- #175
   - [x] local db 
   - [ ] dev db
   - [ ] test db (part of deployment to test)
- [x] get webin auth docs from Dipayan
  - see [webin auth api docs](https://www.ebi.ac.uk/ena/submit/webin/auth/swagger-ui/index.html) 
- define access roles to the system 
  - reader - read only access
  - editor - can create & change checklists - for the ENA team
  - admin - can create users and assign roles
- protect resources
  - [x] checklists modification  (editor)
  - [x] fields fields modification (editor)
  - [x] users (admin)
  - [x] import xmls 
- left accessible anonymously 
  - [x] checklist, fields reading
  - [x] actuator (spring management api)
  - [x] export to json schema

- user onboarding procedure
  - [x] initially - create a user in the db
  - [ ] #183
- [ ] #182

**Comment by amnonkhen** [comment]
Some relevant articles about spring security and implementing access control using a 3rd party service:

- https://engineering.autotrader.co.uk/2021/06/25/sso-with-spring-security.html
- https://medium.com/@vuntt1412/spring-security-custom-authentication-cf781d08c4fc
- https://medium.com/@sallu-salman/understanding-the-key-components-in-spring-security-authentication-245297a40b93

**Comment by amnonkhen** [comment]
The authentication flow is:

```mermaid
sequenceDiagram
    title Checklist Editor Auth syntax

    participant che as ChecklistEditor
    participant sch as SchemaStore
    participant Webin

    che ->> Webin: login (user,pass)<br>POST /auth/token
    Webin -->> che: token
    che ->> sch: any api request <br>w/ Bearer token 
    sch ->> Webin: verify token<br>using /admin/submission-account
    Webin -->> sch: account details
    sch -->> che: auth result
```

We will implement this flow leveraging most of build in spring security features, as in this diagram:

![Image](https://github.com/user-attachments/assets/9bf0be7a-f4d2-498d-8cd2-5e58dc5cbaff)

We will use:
- `BearerTokenAuthenticationFilter` - a spring built in `Filter` class
  1. to read the token from the request
  2. initialise a `BearerTokenAuthenticationToken` with the user supplied token to be passed along the authentication flow.
  3. delegate token verification to the `BearerTokenAuthenticationProvider` authentication provider via the authentication manager
- `BearerTokenAuthenticationProvider` - a home grown `AuthenticationProvider` implementation that verifies the token by sending a rest request to the webin rest api.
- `BearerTokenAuthenticationToken` - a spring built in implementation of the `Authentication` interface.
- This configuration happens in the `SecurityConfig` class
